{% set name = "jupyter_full_width" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9227f315962ce49713f6a9a5f58ca1985ccc666f2f77dc9429fe600b4ad0afd2

build:
  noarch: python
  number: 1
  script:
    - python setup.py install --single-version-externally-managed --record record.txt
    - jupyter nbextension install full_width --py --sys-prefix --overwrite

requirements:
  host:
    - pip
    - python
    - setuptools
    - notebook >=4.0
    - jupyter

  run:
    - python
    - notebook >=4.0
    - jupyter

test:
  imports:
    - full_width

about:
  home: https://github.com/JoaoFelipe/JupyterFullWidth
  license: MIT
  summary: 'Add a button to allow jupyter to use the full browser width'
  license_family: MIT

extra:
  recipe-maintainers:
    - JoaoFelipe
