{% set version = "1.2.0" %}

package:
  name: jupyter_full_width
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_full_width/jupyter_full_width-{{ version }}.tar.gz
  sha256: 9227f315962ce49713f6a9a5f58ca1985ccc666f2f77dc9429fe600b4ad0afd2

build:
  number: 1005
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
    - jupyter nbextension install full_width --py --sys-prefix --overwrite

requirements:
  host:
    - python
    - pip
    - notebook >=4.0
  run:
    - python
    - notebook >=4.0

test:
  imports:
    - full_width

about:
  home: https://github.com/JoaoFelipe/JupyterFullWidth
  license: MIT
  license_file: LICENSE
  summary: 'Add a button to allow jupyter to use the full browser width'
  license_family: MIT

extra:
  recipe-maintainers:
    - JoaoFelipe
