# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Bg7MeRZalHRIr/VpmK5HNPQvl0F7oJWRqkvb0/TEmgJAFANTzVBbgYu2MUUvhBLDg/BiYwA32gfiNafIzK3kFpKiumYPRO80yIZiKzTHrkl5wJ+WtdVA7DQoW5L4RRt3LbYFeU3GzBfn9R6s8DTLJg15xMau5bjQbFyYqlkVfVgXYhO+4mYCKESPyEcdA0dwTjoze9CGb/+zNBL3sRm2k9BDKlw8Pz6qceSl00wsV4lhB7Znko0pR3KRqLVwd/6/XclGHpt+jsWTCPRP0aoQcpEq6lpvudJbs5sjaURdFyCK1mjLza79ZUWXSc3TbG6kGybBIkDpjkUlzpVl2LVQ9tCMHgwXPyWAGN8y5ufqdvFmfS/J+62L9lZ2JmOqnNfyd+Byy8FdYUL185DeJ0lOYHmFmdWsJi2z1rkv6Xx7gRGOPAdMPhzlqobUE1cu8FN0OHHLRSpb4Ru017WWXsWKdrEFLYy+RUbR+SAaG4xbsLTbCFkjfYZ2FF4X0tjB5lieqob/xEf3vxLE4KEPdK/it+d9b4i6mqYyldVXF/Kebx47AdXSjV+BU0rUvE3L86Wzxv+pEVIuMtFLBmWkUvGmsR9pjBPtH/LrZurjjoVEePFCm5t0nlZ4RPpSwviADttWsfefTUdJwBhXJSikXRZV6dAN/ACXkr8FQHAOBSuMAN8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
