travis:
  secure:
    BINSTAR_TOKEN: f52ImDjZGcYCF0FDd7SJ1JDHs5LRxupPGs2WRxpH/rrIwTWSzOuQcCnA7iOhfweLs5jA9ILEQivDud5ke6MvGnrPXo5rMqNs7h72GKzUcQfxwMGf4mYFy8EDll2OeJq9jlO9Tz0qGqBXfTbivHSzT7kaw4OONpVOLn0LM1z7aaS6cr253oUZJVzWRkMmD3jpdrtJZtnAK+MeNClwwH99I9Vwxr7OtjgD1wAaRJ0gT92aKY+Uqran9AHguH2ZstVbNaUeemLpBAYh5X2cAsXU46I+RN5CeZyDCEWjqAzX5RNLOGtDwD8kQFH/EETAGNxn87XWn/f6PVJc09UJlnjnUQvTkTZo3MnoBAmh5S5mWEF4DL5tZIJZhnU0zinFcwUGODSwVh28D670Pigj8fGu0KgeTt/dLMRk7OwhK+auqKhJM96knEguhlel3l32qNhhDGKOSkQzOwKcsbbjHv+k9ICRb3dWM/foc8lB1Q9x3bfDacWXs+Dw1vCDzEb1/aYzAae2QFK9ipt/r9lNeF/Re0Az5iG8unA33l24MK34UUMGcmqoh30jTtEOhno6v9ytCypU9adNCSsAHs5p18BWxJKwGUdmxpIiVVI4OWkmjI3qR+YM/xIPjMJ0BeeOD/hR9Jxt1tkvj08fKhsxUjxPpZkEo49vlMFrAzC9k5BK6lI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
