travis:
  secure:
    BINSTAR_TOKEN: Bg7MeRZalHRIr/VpmK5HNPQvl0F7oJWRqkvb0/TEmgJAFANTzVBbgYu2MUUvhBLDg/BiYwA32gfiNafIzK3kFpKiumYPRO80yIZiKzTHrkl5wJ+WtdVA7DQoW5L4RRt3LbYFeU3GzBfn9R6s8DTLJg15xMau5bjQbFyYqlkVfVgXYhO+4mYCKESPyEcdA0dwTjoze9CGb/+zNBL3sRm2k9BDKlw8Pz6qceSl00wsV4lhB7Znko0pR3KRqLVwd/6/XclGHpt+jsWTCPRP0aoQcpEq6lpvudJbs5sjaURdFyCK1mjLza79ZUWXSc3TbG6kGybBIkDpjkUlzpVl2LVQ9tCMHgwXPyWAGN8y5ufqdvFmfS/J+62L9lZ2JmOqnNfyd+Byy8FdYUL185DeJ0lOYHmFmdWsJi2z1rkv6Xx7gRGOPAdMPhzlqobUE1cu8FN0OHHLRSpb4Ru017WWXsWKdrEFLYy+RUbR+SAaG4xbsLTbCFkjfYZ2FF4X0tjB5lieqob/xEf3vxLE4KEPdK/it+d9b4i6mqYyldVXF/Kebx47AdXSjV+BU0rUvE3L86Wzxv+pEVIuMtFLBmWkUvGmsR9pjBPtH/LrZurjjoVEePFCm5t0nlZ4RPpSwviADttWsfefTUdJwBhXJSikXRZV6dAN/ACXkr8FQHAOBSuMAN8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
