travis:
  secure:
    BINSTAR_TOKEN: FoVe58eYd+cTK3sl97Yc8+4SbuVgHW3TrglRjCTB6oAQ3OlVKH8ZR1qzhVSmd3Yl0UWEC3tPyhlu3oJ1P0J+3vVw837/IzYG7XVY2tf4ic+IeQOV1jyqwGeZwJGxYsiqmEKh1naN+rtVmJGJQ8j/9aw+TORbOzTAY4xqBbuzPeFVKICn4bOGiEHTdycCu8+i+3epn/kZqL+gITnkYoY0TqgE/YuJCTeQFiZaT8Ju1GxY1QYAByK5LV14JUn/4XSpI8hhi4Lx1UHF/T+V81S2twRw0YgOJ4Lw4Hb8mQqmlkYxC7hzIRfCfOICfwcg1sCGW2MNSv2YKhoRFgvnEfJP54Xcxip578hds/F9kMsBueR2XD6i6V1jn3ObxJ3n8b2gaVl83LagR4Ou3k4nMiYMtVGuwbcVVPeCWNaNaQWvICsiUUPU0t7eWELrYqSXiNEZqelFpP/+pQFRVb155mPe3c929akALjvf7GPpNTk2mOXVI4as/ZKF4OVSrNeibAU8l8RMqJtCJPxJxwCnqPgSDxOpBjoDegCHWIjxo/QthLvzoR7svEE7rka7/H7WPYZ0FZcP9s5wy6b69h3u4Kp4HKlebbbiE7nFOpvXfL0AYfyT8b3Y53G6hTV5L2HyVGE84wFhI5+WwPyGK/hKlTE6gqv3nuy2kOIskO+RFfDyLsM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
